config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/index_signed_in'
  get 'search', to: 'home#search'
  get 'show/artists/:artist_id', to: 'home#artist', as: 'artist'
  get 'show/artists/:artist_id/albums/:album_id', to: 'home#album', as: 'album'
  get 'show/artists/:artist_id/albums/:album_id/tracks/:track_id', to: 'home#track', as: 'track'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticated :user do
    root 'home#index_signed_in', as: :authenticated_root
  end

  devise_scope :user do
    root to: 'home#index'
  end

  devise_for :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, except: :index_signed_in
  before_action :find_artist!, only: [:artist,:album, :track ]
  before_action :find_album!, only: [:album, :track ]
  before_action :find_track!, only: [:track ]

  def index
    @artists = Artist.order('created_at desc').limit(10)
    @albums = Album.order('created_at desc').limit(10).includes(:artist)
    @tracks = Track.order('created_at desc').limit(10).includes(album: :artist)
  end

  def index_signed_in
    @artists = Artist.order('created_at desc').limit(10)
    @albums = Album.order('created_at desc').limit(10).includes(:artist)
    @tracks = Track.order('created_at desc').limit(10).includes(album: :artist)
    render :index
  end

  def search
    search_term = "%#{params[:q].to_s}%"
    @artists = Artist.order('created_at desc').where("name ILIKE :search_term", search_term: search_term ).limit(10)
    @albums = Album.order('created_at desc').where("name ILIKE :search_term", search_term: search_term ).limit(10).includes(:artist)
    @tracks = Track.order('created_at desc').where("name ILIKE :search_term", search_term: search_term ).limit(10).includes(album: :artist)
  end

  def artist
    load_similar_artists
  end

  def album
    load_similar_artists
    load_similar_albums
  end

  def track
    load_similar_artists
    load_similar_albums
    load_similar_tracks
  end

  private

  def load_similar_artists

    # find similar artists tagged with the same tags
    @similar_artists =  Artist.tagged_with(@artist.tag_list, :any => true).limit(5)
    # try find artists with albums of the same genre
    @similar_artists = Artist.joins(:albums).where(albums: {genre_id: @artist.albums.pluck(:genre_id)}).where.not(id: @artist.id).limit(5) unless @similar_artists.present?
    # just get available five artists whose names match the artist name
    unless @similar_artists.present?
      terms = []
      keys = []
      @artist.name.split(" ").each{|x| terms << "name ilike ? "; keys << "%#{x}%" }
      @similar_artists = Artist.where.not(id: @artist.id).where(terms.join(' OR '), *keys).limit(5)
    end
    # try load artists in the same age group
    @similar_artists = Artist.where.not(id: @artist.id).where("age between ? and ?", @artist.age - 5, @artist.age + 5).limit(5) unless @similar_artists.present?
    # everything else fails, just load available artists
    @similar_artists = Artist.where.not(id: @artist.id).limit(5)  unless @similar_artists.present?
  end

  def load_similar_albums
    # find similar albums tagged with the same tags
    @similar_albums =   Album.tagged_with(@album.tag_list, :any => true).limit(5)
    # try find albums with albums of the same genre
    @similar_albums = Album.where(genre_id: @album.genre_id).where.not(id: @album.id).limit(5) unless @similar_albums.present?
    # just get available five albums whose names match the album name
    unless @similar_albums.present?
      terms = []
      keys = []
      @album.name.split(" ").each{|x| terms << "name ilike ? "; keys << "%#{x}%" }
      @similar_albums = Album.where.not(id: @album.id).where(terms.join(' OR '), *keys).limit(5)
    end
    # try load albums released at similar time
    @similar_albums = Album.where.not(id: @album.id).where("release_date between ? and  ?", 2.months.since(@album.release_date), 2.months.ago(@album.release_date)).limit(5) unless @similar_albums.present?
    # everything else fails, just load available albums
    @similar_albums = Album.where.not(id: @album.id).limit(5)  unless @similar_albums.present?
  end

  def load_similar_tracks
    # find similar tracks tagged with the same tags
    @similar_tracks =   Track.tagged_with(@track.tag_list, :any => true).limit(5)

    # load tracks of the same artist
    @similar_tracks = Track.where(album_id: @artist.albums.pluck(:id)).where.not(id: @track.id).limit(5) unless @similar_tracks.present?
    # just get available five tracks whose names match the track name
    unless @similar_tracks.present?
      terms = []
      keys = []
      @track.name.split(" ").each{|x| terms << "name ilike ? "; keys << "%#{x}%" }
      @similar_tracks = Track.where.not(id: @track.id).where(terms.join(' OR '), *keys).limit(5)
    end
    # everything else fails, just load available tracks
    @similar_tracks = Track.where.not(id: @track.id).limit(5)  unless @similar_tracks.present?
  end

  def find_artist!
    @artist = Artist.find(params[:artist_id])
  end

  def find_album!
    @album = @artist.albums.find(params[:album_id])
  end

  def find_track!
    @track = @album.tracks.find(params[:track_id])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/album.html.erb
<h3>Album: <%= @album.name %> </h3>
<div class="row">
  <div class="col-md-4">

    <div class="thumbnail">
      <img alt="100%x200" data-src="holder.js/100%x200" style="height: 200px; width: 100%; display: block;" data-holder-rendered="true"  src="<%= @album.cover.try(:url) %>" >
      <div class="caption">
        <h3>Description</h3>
        <p><%= @album.description %></p>
      </div>
    </div>

    <h3>More Info</h3>
    <div class="well well-lg">
      <b>Artist</b>
      <p>
        <img src="<%= @album.artist.picture.try(:thumb).try(:url)%>" alt="artist picture" class="img-thumbnail"><br/>
        <%= link_to @album.artist.name, artist_path(@album.artist) %>
      </p>
      <b>Genre</b>
      <p><%= @album.genre.name %></p>
      <b>Release Date</b>
      <p><%= @album.release_date%></p>
      <b>Duration</b>
      <p><%= @album.duration%></p>
      <b>Recording start date</b>
      <p><%= @album.recording_start_date%></p>
      <b>Recording end date</b>
      <p><%= @album.recording_end_date%></p>
    </div>

    <h3>Moods</h3>
    <div class="well well-lg">
      <p><%= @album.moods.map(&:name).join(", ") %></p>
    </div>
    <h3>Styles</h3>
    <div class="well well-lg">
      <p><%= @album.styles.map(&:name).join(", ") %></p>
    </div>
    <h3>Themes</h3>
    <div class="well well-lg">
      <p><%= @album.styles.map(&:name).join(", ") %></p>
    </div>
    <h3>Tags</h3>
    <div class="well well-lg"><%= @album.tag_list.presence || 'No tags' %></div>

    <h3>Credits</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Credit</th>
          <th>Type</th>
        </tr>
      </thead>
      <tbody>
        <% @credits = @album.album_credits %>
        <% if @credits.present? %>
          <% @credits.each do |credit| %>
          <tr>
            <td><%= credit.credit %></td>
            <td><%= credit.credit_type.name %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No credits</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-md-8">
    <h3>Tracks</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Track</th>
          <th>Duration</th>
        </tr>
      </thead>
      <tbody>
        <% @tracks = @album.tracks %>
        <% if @tracks.present? %>
          <% @tracks.each do |track| %>
          <tr>
            <td><%= link_to  track.track_number, track_path(track.album.artist, track.album, track)  %>.  <%= link_to track.name, track_path(track.album.artist, track.album, track) %></td>
            <td><%= track.duration %> </td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No tracks</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h3>Similar albums</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
          <th>Album</th>
        </tr>
      </thead>
      <tbody>
        <% if @similar_albums.present? %>
          <% @similar_albums.each do |album| %>
          <tr>
            <td>
               <img src="<%= album.artist.picture.try(:thumb).try(:url)%>" alt="artist picture" class="img-thumbnail"><br/>
               <%= link_to album.artist.name, artist_path(album.artist) %></td>
            <td>
              <img src="<%= album.cover.try(:thumb).try(:url)%>" alt="album cover" class="img-thumbnail"><br/>
              <%= link_to album.name, album_path(album.artist, album) %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No matching results</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h3>Similar artists</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
        </tr>
      </thead>
      <tbody>
        <% if @similar_artists.present? %>
          <% @similar_artists.each do |artist| %>
          <tr>
            <td>
              <img src="<%= artist.picture.try(:thumb).try(:url)%>" alt="thumb" class="img-thumbnail"><br/>
              <%= link_to artist.name, artist_path(artist) %>
            </td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No matching results</td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/home/artist.html.erb
<h3>Artist: <%= @artist.name %></h3>
<div class="row">
  <div class="col-md-4">

    <div class="thumbnail">
      <img alt="100%x200" data-src="holder.js/100%x200" style="height: 200px; width: 100%; display: block;" data-holder-rendered="true"  src="<%= @artist.picture.try(:url) %>" >
      <div class="caption">
        <h3>Biography</h3>
        <p><%= @artist.biography %></p>
      </div>
    </div>
    <h3>Tags</h3>
    <div class="well well-lg"><%= @artist.tag_list.presence || 'No tags' %></div>
  </div>
  <div class="col-md-4">
    <h3>Albums</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Album</th>
          <th>Genre</th>
        </tr>
      </thead>
      <tbody>
        <% @albums = @artist.albums %>
        <% if @albums.present? %>
          <% @albums.each do |album| %>
          <tr>
            <td><%= link_to album.name, album_path(album.artist, album) %></td>
            <td><%= album.genre.name %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No albums</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h3>Tracks</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Album</th>
          <th>Track</th>
        </tr>
      </thead>
      <tbody>
        <% @tracks = @artist.tracks %>
        <% if @tracks.present? %>
          <% @tracks.each do |track| %>
          <tr>
            <td><%= link_to track.album.name, album_path(@artist, track.album) %></td>
            <td><%= link_to track.name, track_path(track.album.artist, track.album, track) %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No tracks</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">
    <h3>Similar artists</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
        </tr>
      </thead>
      <tbody>
        <% if @similar_artists.present? %>
          <% @similar_artists.each do |artist| %>
          <tr>
            <td>
              <img src="<%= artist.picture.try(:thumb).try(:url)%>" alt="thumb" class="img-thumbnail"><br/>
              <%= link_to artist.name, artist_path(artist) %>
            </td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No matching results</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<%= form_tag '/search', method: "GET" do  %>
  <div class="container">
  	<div class="row">
        <div class="col-md-6">
      		<h2>Search artists, albums and tracks</h2>
          <div id="custom-search-input">
              <div class="input-group col-md-12">
                <span class="input-group-btn">
                  <a class="btn btn-default btn-lg" href='/'>
                      <i class="glyphicon glyphicon-reset"></i> Reset
                  </a>
                </span>
                  <input type="text" name='q' class="form-control input-lg" placeholder="Search...." value="<%= params[:q] %>" />
                  <span class="input-group-btn">
                      <button class="btn btn-info btn-lg" type="submit">
                          <i class="glyphicon glyphicon-search"></i>Search
                      </button>
                  </span>
              </div>
          </div>
        </div>
  	</div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-3">
    <h3> New Artists</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
        </tr>
      </thead>
      <tbody>
        <% if @artists.present? %>
          <% @artists.each do |artist| %>
          <tr>
            <td>
              <img src="<%= artist.picture.try(:thumb).try(:url)%>" alt="thumb" class="img-thumbnail"><br/>
              <%= link_to artist.name, artist_path(artist) %>
            </td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No matching results</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">
    <h3>New Albums</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
          <th>Album</th>
        </tr>
      </thead>
      <tbody>
        <% if @albums.present? %>
          <% @albums.each do |album| %>
          <tr>
            <td>
               <img src="<%= album.artist.picture.try(:thumb).try(:url)%>" alt="artist picture" class="img-thumbnail"><br/>
               <%= link_to album.artist.name, artist_path(album.artist) %></td>
            <td>
              <img src="<%= album.cover.try(:thumb).try(:url)%>" alt="album cover" class="img-thumbnail"><br/>
              <%= link_to album.name, album_path(album.artist, album) %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No matching results</td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>
  <div class="col-md-5">
    <h3>New Tracks</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
          <th>Album</th>
          <th>Track</th>
        </tr>
      </thead>
      <tbody>
        <% if @tracks.present? %>
          <% @tracks.each do |track| %>
          <tr>
            <td>
              <img src="<%= track.album.artist.picture.try(:thumb).try(:url)%>" alt="artist picture" class="img-thumbnail"><br/>
              <%= link_to track.album.artist.name, artist_path(track.album.artist) %>
            </td>
            <td>
              <img src="<%= track.album.cover.try(:thumb).try(:url)%>" alt="album cover" class="img-thumbnail"><br/>
              <%= link_to track.album.name, album_path(track.album.artist, track.album) %>
            </td>
            <td><%= link_to track.name, track_path(track.album.artist, track.album, track) %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No matching results</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/search.html.erb
<%= form_tag '/search', method: "GET" do  %>
  <div class="container">
  	<div class="row">
          <div class="col-md-6">
      		<h2>Search artists, albums and tracks</h2>
          <div id="custom-search-input">
              <div class="input-group col-md-12">
                <span class="input-group-btn">
                  <a class="btn btn-default btn-lg" href='/'>
                      <i class="glyphicon glyphicon-reset"></i> Reset
                  </a>
                </span>
                  <input type="text" name='q' class="form-control input-lg" placeholder="Search...." value="<%= params[:q] %>" />
                  <span class="input-group-btn">
                      <button class="btn btn-info btn-lg" type="submit">
                          <i class="glyphicon glyphicon-search"></i>Search
                      </button>
                  </span>
              </div>
          </div>
        </div>
  	</div>
  </div>
<% end %>
<h3>Search Results</h3>
<div class="row">
  <div class="col-md-3">
    <h3> Artists</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
        </tr>
      </thead>
      <tbody>
        <% if @artists.present? %>
          <% @artists.each do |artist| %>
          <tr>
            <td>
              <img src="<%= artist.picture.try(:thumb).try(:url)%>" alt="thumb" class="img-thumbnail"><br/>
              <%= link_to artist.name, artist_path(artist) %>
            </td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No matching results</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">
    <h3>Albums</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
          <th>Album</th>
        </tr>
      </thead>
      <tbody>

        <% if @albums.present? %>
          <% @albums.each do |album| %>
          <tr>
            <td>
               <img src="<%= album.artist.picture.try(:thumb).try(:url)%>" alt="artist picture" class="img-thumbnail"><br/>
               <%= link_to album.artist.name, artist_path(album.artist) %></td>
            <td>
              <img src="<%= album.cover.try(:thumb).try(:url)%>" alt="album cover" class="img-thumbnail"><br/>
              <%= link_to album.name, album_path(album.artist, album) %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan='2'>No matching results</td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>
  <div class="col-md-5">
    <h3>Tracks</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
          <th>Album</th>
          <th>Track</th>
        </tr>
      </thead>
      <tbody>
        <% if @tracks.present? %>
          <% @tracks.each do |track| %>
          <tr>
            <td>
              <img src="<%= track.album.artist.picture.try(:thumb).try(:url)%>" alt="artist picture" class="img-thumbnail"><br/>
              <%= link_to track.album.artist.name, artist_path(track.album.artist) %>
            </td>
            <td>
              <img src="<%= track.album.cover.try(:thumb).try(:url)%>" alt="album cover" class="img-thumbnail"><br/>
              <%= link_to track.album.name, album_path(track.album.artist, track.album) %>
            </td>
            <td><%= link_to track.name, track_path(track.album.artist, track.album, track) %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan='3'>No matching results</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/track.html.erb
<h3>Track: <%= @track.name %></h3>
<div class="row">
  <div class="col-md-4">
    <h3>Track Info</h3>
    <div class="well well-lg">
      <b>Artist</b>
      <p>
        <img src="<%= @track.album.artist.picture.try(:thumb).try(:url)%>" alt="artist picture" class="img-thumbnail"><br/>
        <%= link_to @track.album.artist.name, artist_path(@track.album.artist) %>
      </p>
      <b>Album</b>
      <p>
        <img src="<%= @track.album.cover.try(:thumb).try(:url)%>" alt="album cover" class="img-thumbnail"><br/>
        <%= link_to @track.album.name, album_path(@track.album.artist, @track.album) %>
      </p>

      <b>Name</b>
      <p><%= @track.name %></p>
      <b>Duration</b>
      <p><%= @track.duration%></p>
      <b>Track number</b>
      <p><%= @track.track_number%></p>
    </div>
    <h3>Tags</h3>
    <div class="well well-lg"><%= @album.tag_list.presence || 'No tags' %></div>
    <h3>Credits</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Credit</th>
          <th>Type</th>
        </tr>
      </thead>
      <tbody>
        <% @credits = @track.track_credits %>
        <% if @credits.present? %>
          <% @credits.each do |credit| %>
          <tr>
            <td><%= credit.credit %></td>
            <td><%= credit.credit_type.name %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No credits</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-8">

    <h3>Similar tracks</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
          <th>Album</th>
          <th>Track</th>
        </tr>
      </thead>
      <tbody>
        <% if @similar_tracks.present? %>
          <% @similar_tracks.each do |track| %>
          <tr>
            <td>
              <img src="<%= track.album.artist.picture.try(:thumb).try(:url)%>" alt="artist picture" class="img-thumbnail"><br/>
              <%= link_to track.album.artist.name, artist_path(track.album.artist) %>
            </td>
            <td>
              <img src="<%= track.album.cover.try(:thumb).try(:url)%>" alt="album cover" class="img-thumbnail"><br/>
              <%= link_to track.album.name, album_path(track.album.artist, track.album) %>
            </td>
            <td><%= link_to track.name, track_path(track.album.artist, track.album, track) %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan='3'>No matching results</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h3>Similar albums</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
          <th>Album</th>
        </tr>
      </thead>
      <tbody>
        <% if @similar_albums.present? %>
          <% @similar_albums.each do |album| %>
          <tr>
            <td>
               <img src="<%= album.artist.picture.try(:thumb).try(:url)%>" alt="artist picture" class="img-thumbnail"><br/>
               <%= link_to album.artist.name, artist_path(album.artist) %></td>
            <td>
              <img src="<%= album.cover.try(:thumb).try(:url)%>" alt="album cover" class="img-thumbnail"><br/>
              <%= link_to album.name, album_path(album.artist, album) %></td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No matching results</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h3>Similar artists</h3>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
        <tr>
          <th>Artist Name</th>
        </tr>
      </thead>
      <tbody>
        <% if @similar_artists.present? %>
          <% @similar_artists.each do |artist| %>
          <tr>
            <td>
              <img src="<%= artist.picture.try(:thumb).try(:url)%>" alt="thumb" class="img-thumbnail"><br/>
              <%= link_to artist.name, artist_path(artist) %>
            </td>
          </tr>
          <% end %>
        <% else %>
          <tr>
            <td>No matching results</td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>



</div>