config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/index_signed_in'
  get 'search', to: 'home#search'
  get 'show/artists/:artist_id', to: 'home#artist', as: 'artist'
  get 'show/artists/:artist_id/albums/:album_id', to: 'home#album', as: 'album'
  get 'show/artists/:artist_id/albums/:album_id/tracks/:track_id', to: 'home#track', as: 'track'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticated :user do
    root 'home#index_signed_in', as: :authenticated_root
  end

  devise_scope :user do
    root to: 'home#index'
  end

  devise_for :users

end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/views/admin/base/index.html.erb
<h3>Admin Section</h3>
<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a  data-href="<%=   admin_artists_path   %>" data-target='#artists' aria-controls="artists" role="tab" data-toggle="tab">Artists</a></li>
    <li role="presentation" class=""><a data-href="<%=  admin_albums_path  %>" data-target='#albums' aria-controls="albums" role="tab" data-toggle="tab">Albums</a></li>
    <li role="presentation" class=""><a data-href="<%=  admin_genres_path  %>" data-target='#genres'  aria-controls="genres" role="tab" data-toggle="tab">Genres</a></li>
    <li role="presentation" class=""><a data-href="<%=  admin_moods_path  %>" data-target='#moods'  aria-controls="moods" role="tab" data-toggle="tab">Moods</a></li>
    <li role="presentation" class=""><a data-href="<%=  admin_styles_path  %>" data-target='#styles'  aria-controls="styles" role="tab" data-toggle="tab">Styles</a></li>
    <li role="presentation" class=""><a data-href="<%=  admin_themes_path  %>" data-target='#themes'  aria-controls="themes" role="tab" data-toggle="tab">Themes</a></li>
    <li role="presentation" class=""><a data-href="<%=  admin_credit_types_path  %>" data-target='#credit_types'  aria-controls="credit_types" role="tab" data-toggle="tab">Credit Types</a></li>
    <li role="presentation" class=""><a data-href="<%=  admin_users_path  %>" data-target='#users'  aria-controls="users" role="tab" data-toggle="tab">Users</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane  active" id='artists'>
      <%= render  :active_scaffold => "admin/artists" %>
    </div>
    <div role="tabpanel" class="tab-pane" id='albums'></div>
    <div role="tabpanel" class="tab-pane" id='genres'></div>
    <div role="tabpanel" class="tab-pane" id='moods'></div>
    <div role="tabpanel" class="tab-pane" id='styles'></div>
    <div role="tabpanel" class="tab-pane" id='themes'></div>
    <div role="tabpanel" class="tab-pane" id='credit_types'></div>
    <div role="tabpanel" class="tab-pane" id='users'></div>
  </div>

</div>